### ISSUE TITLE
Glossy-Style Carbon Fibre Navigation Buttons

### ISSUE THREAD

**Issue by mono0926** [mono0926/SheepHomework#1]
# [Glossy-Style Carbon Fibre Navigation Buttons](http://www.photoshopstar.com/web-design/glossy-style-carbon-fibre-navigation-set/)

**Comment by mono0926** [comment]
~~先生、ブラシのインストールがよく分かりません（´・ω・｀）~~解決

> Download some free brushes and install them, then do a little bit of brushing in the corners, remember to mess around with different layer modes and opacities.

**Comment by mono0926** [comment]
先生、何すればいいのか分かりません（´・ω・｀）

> You can finish the background off by flattening the image, duplicating the remaining layer, applying some layer styles then messing with the layer modes, this gives the whole background a bit of a nicer contrast, I think ;)

**Comment by mono0926** [comment]
~~先生、何の意味があるのか分かりません（´・ω・｀)~~ 分かった(　´･‿･｀)

> After selecting your buttons, contract the selection by about 2 pixels, you can do this by going to Select > Modify > Contract in the Photoshop menus.

**Comment by mono0926** [comment]
先生、フォントを一気に変えたい時はどうすれば(　´･‿･｀)

**Comment by mono0926** [comment]
先生、黒いdropshadowかけても意味なしお君ではないですか？（´・ω・｀）

> I also applied this (Drop Shadow) to my each of my navigation text layers.

**Comment by mono0926** [comment]
完成品ヽ(・ω・｀）
![image](https://raw.github.com/mono0926/SheepHomework/master/photoshop/navigationButtons/navigation_button.jpg)

**Comment by memesheep** [comment]
test

**Comment by memesheep** [comment]
~~あいうえお~~解決

**Comment by memesheep** [comment]
[ブラシ追加方法](http://www.fmod.jp/qp/30/30.html)
