### ISSUE TITLE
How to Create Realistic Vector Leaves in Illustrator

### ISSUE THREAD

**Issue by memesheep** [mono0926/SheepHomework#10]
ベジェ＋グラデーションツールに慣れるチュートリアル
[How to Create Realistic Vector Leaves in Illustrator](http://vectips.com/tutorials/how-to-create-realistic-vector-leaves-in-illustrator/)

**Comment by mono0926** [comment]
ありがとうございます(　´･‿･｀)

**Comment by mono0926** [comment]
> Step 17
> Turn the Grayscale color mode in the Color panel, then reduce the K value to get the desired intensity of the veins’ color.

ここのやり方が分からなくて[漫画](http://www.amazon.co.jp/gp/product/B00I14BMD6/ref=as_li_ss_tl?ie=UTF8&camp=247&creative=7399&creativeASIN=B00I14BMD6&linkCode=as2&tag=mono0926-22)を読み始めた次第です(　´･‿･｀)
