### ISSUE TITLE
Create a Set of “Almost Flat” Modern Icons in Adobe Illustrator

### ISSUE THREAD

**Issue by memesheep** [mono0926/SheepHomework#11]
前にちょこっとIllustratorやったときにでてきた、パスファインダーとアピアランスの練習
[Create a Set of “Almost Flat” Modern Icons in Adobe Illustrator](http://vector.tutsplus.com/tutorials/designing/create-a-set-of-almost-flat-modern-icons-in-adobe-illustrator/)

**Comment by mono0926** [comment]
多いですね（´・ω・｀）

**Comment by memesheep** [comment]
先生、明日から雪国いってくるからその間の宿題です

**Comment by mono0926** [comment]
（´・ω・｀）
