### ISSUE TITLE
スタンプのお手本作る

### ISSUE THREAD

**Issue by mono0926** [mono0926/SheepHomework#18]
結局どれが良いのですかね。
- Photoshop
- Illustrator
- Fireworks

**Comment by mono0926** [comment]
素材は、とりあえず上でコミットしたLove.aiと[ラヴさんアルバム](http://a.scn.jp/s/pc/7D0zER2AB)がございます(　´･‿･｀)

**Comment by mono0926** [comment]
現状のラヴさんアイコンはなんだかんだ気に入っているので、このテイストで色々な表情・仕草を量産したく思ってます(　´･‿･｀)

**Comment by memesheep** [comment]
いつのまにかこんなIssueがコミットされていてびっくりしているたん
Retinaレベルにまで解像度上がってくると個人的には、イラレベジェでやるのが綺麗かなと（一個作ってみてLineに貼り付けてみます）

**Comment by mono0926** [comment]
さすが神ひつじさん

**Comment by mono0926** [comment]
ありがとうございます(　´･‿･｀)

#15に引き継ぎます(　´･‿･｀)
