### ISSUE TITLE
iOS7 Blur effect

### ISSUE THREAD

**Issue by mono0926** [mono0926/SheepHomework#4]
[iOS7 Blur effect](http://www.behance.net/gallery/iOS7-Blur-effect/10702833)

**Comment by mono0926** [comment]
blending optionsで透明度変えるのと、レイヤーの透明度を変えるのは何が違うんですか？(　´･‿･｀)

**Comment by memesheep** [comment]
@mono0926 blending optionもレイヤーの透明度も同じです！blending option＝レイヤー効果で、その中の透明度を変える＝レイヤーの透明度を変える　ということです
実際、blending optionのレイヤー透明度を変えてOKするとレイヤーの透明度も同じ値に変更されているはずです。

**Comment by mono0926** [comment]
ありがとうございます、確かに(　´･‿･｀)
