### ISSUE TITLE
Realistic Makeup Application in Photoshop

### ISSUE THREAD

**Issue by memesheep** [mono0926/SheepHomework#5]
ペンタブに慣れようということで、女性のノーメイク画像をPhotoshopでお化粧してあげる課題です。

[Realistic Makeup Application in Photoshop](http://psd.tutsplus.com/tutorials/photo-effects-tutorials/realistic-makeup-application/)

**Comment by mono0926** [comment]
# 作業開始なう

**Comment by memesheep** [comment]
![a4475d0f](https://f.cloud.github.com/assets/1861547/2058740/af9201f2-8b81-11e3-9f91-11d5c2a1fb0b.jpg)
すっぴん
