### ISSUE TITLE
ペンタブの調整

### ISSUE THREAD

**Issue by memesheep** [mono0926/SheepHomework#6]
ペンタブレットは自分の手の感覚や筆圧に合わせた設定を行うことによって使いやすさが格段に変わってきます。設定に関しては以下のリンクを参考にしてみてください。

最初はタブレットの滑りのよさに使いにくさを感じることも多いので、タブレットの上に１枚紙を置いてその上から描いてみる所から初めても良いかもしれません。
### 参考リンク
- [ペンタブレットの基本的な使い方 (by Wacom)](http://tablet.wacom.co.jp/technic/usage.html)
- [ペンタブレットの設定を変えたら世界が変わるかもしれないと聞いて (by Cyber stage)](http://cyberstage0.blog55.fc2.com/blog-entry-43.html)
- [Photoshopでのタブレットの入力情報の設定 (by Adobe)](http://helpx.adobe.com/jp/photoshop/kb/5783.html)

**Comment by mono0926** [comment]
@memesheep めんしょん出来るのか

**Comment by mono0926** [comment]
おわた
