### ISSUE TITLE
ペンタブのファンクションキー割当について

### ISSUE THREAD

**Issue by memesheep** [mono0926/SheepHomework#7]
私の場合は、以下を割り当てて使っています
-  ブラシウィンドウの表示（F5）
- トーンカーブ（command+M）
- 描画色と背景色の入れ替え(X）
- 画面解像度（option+command+I）
  （私の使ってるペンタブ[Intuos5](http://www.amazon.co.jp/Wacom-%E3%83%97%E3%83%AD%E3%83%95%E3%82%A7%E3%83%83%E3%82%B7%E3%83%A7%E3%83%8A%E3%83%AB%E3%83%9A%E3%83%B3%E3%82%BF%E3%83%96%E3%83%AC%E3%83%83%E3%83%88-Intuos5-PTK-650-K0/dp/B007EJ7FMG%3FSubscriptionId%3D0571BBGTQZ5YYPEDSY02%26tag%3Dkakaku-pc-pcother-22%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB007EJ7FMG%26me%3dAN1VRQENFRJN5)は、８つ登録できるのと、タッチホイールとかもあるのでかなり登録しているのですが主に使ってるのは上の４つです（プチ自慢））

選ぶ理由としては、

使う機能＞ショートカットキーで存在するけどキー数が多いもの＞他

みたいなかんじです。

**Comment by mono0926** [comment]
ありがとうございます(　´･‿･｀)

**Comment by mono0926** [comment]
おいおい設定します。
とりあえず[Wiki](https://github.com/mono0926/SheepHomework/wiki/%E3%83%9A%E3%83%B3%E3%82%BF%E3%83%96%E3%81%AE%E3%83%95%E3%82%A1%E3%83%B3%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%AD%E3%83%BC%E5%89%B2%E5%BD%93)に転記しました。
