### ISSUE TITLE
Create a Mobile Weather App Interface in Photoshop

### ISSUE THREAD

**Issue by memesheep** [mono0926/SheepHomework#8]
お天気アプリUIをPhotoshopで作ってみましょう
[Create a Mobile Weather App Interface in Photoshop](http://psd.tutsplus.com/tutorials/interface-tutorials/mobile-weather-app-interface-photoshop/)

**Comment by mono0926** [comment]
先生ありがとうございます。
大変そうで辛いです(　´･‿･｀)

**Comment by mono0926** [comment]
> Check the Add button from the top bar then simply add a 30px circle as shown in the second image. 
> ないです（´-ω-｀）
> ![hoge](http://cdn.tutsplus.com/psd/uploads/2013/12/0933_Weather_App_weatherAppInterface3.jpg)

**Comment by mono0926** [comment]
combine shapes疑惑(　´･‿･｀)

**Comment by mono0926** [comment]
完成ヽ(・ω・｀）
![image](https://raw.github.com/mono0926/SheepHomework/master/photoshop/%238/weather.jpg)

**Comment by mono0926** [comment]
そういえば、こんな話があったり(　´･‿･｀)

#### [#GITHUBJP でGitの話を聞いてきた。−大学の授業とGithubについて聞いてきた](http://pastak.hatenablog.com/entry/2013/11/20/131708)

**Comment by mono0926** [comment]
完了化しますが、おかしいところあったらご指摘ください(　´･‿･｀)

hiとの並びだけ目分量です（´-ω-｀）

あと、例えば曜日ごとにグループ化したんですが、その後最高気温ごとにレイヤーリンクしたら、あとで再度曜日ごとに垂直位置を揃えるときに最高気温同士がぐしゃっとなってしまったので、レイヤーリンクは切りました。
やり方や使う場面微妙ですかね。
グループ自体はけっこうキレイに分けておきました。
